# Generated by Django 5.1.5 on 2025-03-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_disciplina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(max_length=255)),
                ('capacidade', models.IntegerField()),
                ('responsavel', models.CharField(max_length=255)),
                ('periodo', models.CharField(choices=[('M', 'M'), ('T', 'T'), ('N', 'N'), ('S', 'S')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('CAI', 'CAI'), ('CT', 'CT'), ('CS', 'CS'), ('FIC', 'FIC')], max_length=3)),
                ('hora_aula', models.IntegerField()),
                ('sigla', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
    ]
